export * from './shared.module';
export * from './shared.service';
export * from './dtos/auth/loginDTO';
export * from './dtos/auth/registerDTO';
export * from './enums/userRole.Enum';
export * from './dtos/gyms/registerClientDTO';
export * from './dtos/gyms/registerGymDTO';
export * from './dtos/gyms/getGymDTO';
export * from './dtos/gyms/gymSearchByDistanceDTO';